from pcloud import PyCloud
import requests
import json
import os
import datetime


pc = PyCloud('lykangforever@gmail.com', 'lykang.0804', endpoint="eapi")
token_str = pc.get_auth_token()


# Define a function to extract and convert the date value
def get_date(d):
    return datetime.datetime.strptime(d['created'], '%a, %d %b %Y %H:%M:%S %z')


def manual_delete_token(tokenid):
    import requests
    url = f'https://eapi.pcloud.com/deletetoken?tokenid={tokenid}&auth={token_str}'
    response = requests.request("GET", url)
    return json.loads(response.text)

def upload_transfer(filepath):
    url = 'https://api.pcloud.com/uploadtransfer'
    params = {
        'language': 'en',
        'ppaccepted': 'yes',
        'sendermail': 'lykangforever@gmail.com',
        'getlink': '1',
        'locationid': '2',
        'ts': '1691115114',
        'sig': '69210255c78f45bf5fe295aa41a4fb258182349c',
        'auth': token_str
    }

    # Open the file to be uploaded
    basename = os.path.basename(filepath)
    files=[
      ('files',(basename,open(filepath,'rb'),'application/octet-stream'))
    ]
    # Create the form-data request
    response = requests.post(url, data=params, files=files)

    print(response.text)
    # Parse the JSON response
    return json.loads(response.text)


file_path = '/root/nerd-fonts/glyphnames.json'
resp_json = upload_transfer(file_path)
print(resp_json)
code = resp_json['code']
with open("file.txt", "w") as f:
    f.truncate()
    f.write(code)

tokenList = pc.listtokens()['tokens']
sorted_tokenList = sorted(tokenList, key=get_date)
print(len(tokenList))

# delete old tokens generated by 'python-request'
for tokenItem in sorted_tokenList[:-1]:
    print(tokenItem)
    device = tokenItem['device']
    tokenid = tokenItem['tokenid']
    # print(device, tokenid)
    if 'python-request' in device:
        # print('TODO: delete', tokenid)
        resp_json = manual_delete_token(tokenid)
        print('delete token', tokenid, ', resp: ', resp_json)

pc.logout()
